services:
  - type: web
    name: campus-ratings
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.16.11
      - key: DATABASE_URL
        sync: false
